# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: module_4/docs/source/conf.py
  builder: html

python:
  install:
    - requirements: module_4/src/requirements.txt
